import mongoose from "mongoose";

export const oldCourts = [
  {
    name: "BARICHO LAW COURTS",
  },
  {
    name: "BOMET HIGH COURT",
  },
  {
    name: "BOMET LAW COURTS",
  },
  {
    name: "BONDO LAW COURTS",
  },
  {
    name: "BUNGOMA HIGH COURT",
  },
  {
    name: "BUNGOMA LAW COURTS",
  },
  {
    name: "BUSIA HIGH COURT",
  },
  {
    name: "BUSIA LAW COURTS",
  },
  {
    name: "BUTALI LAW COURTS",
  },
  {
    name: "BUTERE LAW COURTS",
  },
  {
    name: "CHUKA HIGH COURT",
  },
  {
    name: "CHUKA LAW COURTS",
  },
  {
    name: "DADAAB LAW COURTS",
  },
  {
    name: "DAGORETTI LAW COURTS",
  },
  {
    name: "ELDAMA – RAVINE LAW COURTS",
  },
  {
    name: "ELDORET HIGH COURT",
  },
  {
    name: "ELDORET LAW COURTS",
  },
  {
    name: "EMBU HIGH COURT",
  },
  {
    name: "EMBU LAW COURTS",
  },
  {
    name: "ENGINEER LAW COURTS",
  },

  {
    name: "ETAGO LAW COURTS",
  },
  {
    name: "GARISSA HIGH COURT",
  },
  {
    name: "GARISSA LAW COURTS",
  },
  {
    name: "GARSEN HIGH COURT",
  },
  { name: "GATUNDU LAW COURTS" },
  { name: "GICHUGU LAW COURTS" },
  { name: "GITHONGO LAW COURTS" },
  { name: "GITHUNGURI LAW COURTS" },
  { name: "HAMISI LAW COURTS" },
  { name: "HOMABAY HIGH COURT" },
  { name: "HOMABAY LAW COURTS" },
  { name: "ISIOLO HIGH COURT" },
  { name: "ISIOLO LAW COURTS" },
  { name: "ITEN HIGH COURT (SUB-REGISTRY)" },
  { name: "ITEN LAW COURTS" },
  { name: "JKIA LAW COURTS" },
  { name: "KABARNET HIGH COURT" },
  { name: "KABARNET LAW COURTS" },
  { name: "KABIYET LAW COURTS" },
  { name: "KAHAWA LAW COURTS" },
  { name: "KAJIADO HIGH COURT" },
  { name: "KAJIADO LAW COURTS" },
  { name: "KAKAMEGA HIGH COURT" },
  { name: "KAKAMEGA LAW COURTS" },

  { name: "KAKUMA LAW COURTS" },
  { name: "KALOLENI LAW COURTS" },
  { name: "KAMWANGI LAW COURTS" },
  { name: "KANDARA LAW COURTS" },
  { name: "KANGEMA LAW COURTS" },
  { name: "KANGUNDO LAW COURTS" },
  { name: "KAPENGURIA HIGH COURT" },
  { name: "KAPENGURIA LAW COURTS" },
  { name: "KAPSABET HIGH COURT" },
  { name: "KAPSABET LAW COURTS" },
  { name: "KARATINA LAW COURTS" },
  { name: "KEHANCHA LAW COURTS" },
  { name: "KENDU BAY LAW COURTS" },
  { name: "KENOL LAW COURTS" },
  { name: "KERICHO HIGH COURT" },
  { name: "KERICHO LAW COURTS" },
  { name: "KEROKA LAW COURTS" },
  { name: "KERUGOYA HIGH COURT" },
  { name: "KERUGOYA LAW COURTS" },
  { name: "KIAMBU HIGH COURT" },
  { name: "KIAMBU LAW COURTS" },
  { name: "KIBERA HIGH COURT" },
  { name: "KIBERA LAW COURTS" },
  { name: "KIGUMO LAW COURTS" },
  { name: "KIKUYU LAW COURTS" },
  { name: "KILGORIS HIGH COURT (SUB-REGISTRY)" },
  { name: "KILGORIS LAW COURTS" },

  { name: "KILUNGU LAW COURTS" },
  { name: "KIMILILI LAW COURTS" },
  { name: "KISII HIGH COURT" },
  { name: "KISII LAW COURTS" },
  { name: "KISUMU HIGH COURT" },
  { name: "KISUMU LAW COURTS" },
  { name: "KITALE HIGH COURT" },
  { name: "KITALE LAW COURTS" },
  { name: "KITHIMANI LAW COURTS" },
  { name: "KITUI HIGH COURT" },
  { name: "KITUI LAW COURTS" },
  { name: "KWALE HIGH COURT" },
  { name: "KWALE LAW COURTS" },
  { name: "KYUSO LAW COURTS" },
  { name: "LAMU LAW COURT" },
  { name: "LAMU HIGH COURT (SUB-REGISTRY)" },
  { name: "LIMURU LAW COURTS" },
  { name: "LODWAR HIGH COURT" },
  { name: "LODWAR LAW COURTS" },
  { name: "LOITOKTOK LAW COURTS" },
  { name: "MACHAKOS HIGH COURT" },
  { name: "MACHAKOS LAW COURTS" },
  { name: "MACHAKOS KADHIS COURT" },
  { name: "MADIANY LAW COURTS" },

  { name: "MAKADARA HIGH COURT" },
  { name: "MAKADARA LAW COURTS" },
  { name: "MAKINDU LAW COURTS" },
  { name: "MAKUENI HIGH COURT" },
  { name: "MAKUENI LAW COURTS" },
  { name: "MALABA LAW COURTS" },
  { name: "MALINDI HIGH COURT" },
  { name: "MALINDI LAW COURTS" },
  { name: "MANDERA HIGH COURT (SUB-REGISTRY)" },
  { name: "MANDERA LAW COURT" },
  { name: "MARALAL HIGH COURT (SUB-REGISTRY)" },
  { name: "MARALAL LAW COURTS" },
  { name: "MARIAKANI LAW COURTS" },
  { name: "MARIMANTI LAW COURTS" },
  { name: "MARSABIT HIGH COURT" },
  { name: "MARSABIT LAW COURTS" },
  { name: "MASENO LAW COURTS" },
  { name: "MAUA LAW COURTS" },
  { name: "MAVOKO LAW COURTS" },
  { name: "MBITA LAW COURTS" },
  { name: "MERU HIGH COURT" },
  { name: "MERU LAW COURTS" },
  { name: "MIGORI HIGH COURT" },
  { name: "MIGORI LAW COURTS" },
  { name: "NAIROBI CHIEF MAGISTRATES COURT" },
  { name: "MILIMANI H.C FAMILY DIVISION" },
  { name: "MOIBEN LAW COURTS" },
  { name: "MOLO LAW COURTS" },
  { name: "MOMBASA HIGH COURT" },
  { name: "MOMBASA LAW COURTS" },
  { name: "MOYALE LAW COURTS" },
  { name: "MSAMBWENI LAW COURTS" },
  { name: "MUKURWEINI LAW COURT" },
  { name: "MUMIAS LAW COURTS" },
  { name: "MURANG’A LAW COURTS" },

  { name: "MURANG’A HIGH COURT" },
  { name: "MUTOMO LAW COURTS" },
  { name: "MWINGI LAW COURTS" },
  { name: "NAIVASHA HIGH COURT" },
  { name: "NAIVASHA LAW COURTS" },
  { name: "NAKURU HIGH COURT" },
  { name: "NAKURU LAW COURTS" },
  { name: "NANYUKI HIGH COURT" },
  { name: "NANYUKI LAW COURTS" },
  { name: "NAROK HIGH COURT" },
  { name: "NAROK LAW COURTS" },
  { name: "NDHIWA LAW COURTS" },
  { name: "NGONG LAW COURTS" },
  { name: "NKUBU LAW COURTS" },
  { name: "NYAHURURU HIGH COURT" },
  { name: "NYAHURURU LAW COURTS" },
  { name: "NYAMIRA HIGH COURT" },
  { name: "NYAMIRA LAW COURTS" },
  { name: "NYANDARUA HIGH COURT" },
  { name: "NYANDO LAW COURTS" },
  { name: "NYERI HIGH COURT" },
  { name: "NYERI LAW COURTS" },
  { name: "OGEMBO LAW COURTS" },
  { name: "OL KALOU LAW COURTS" },
  { name: "OTHAYA LAW COURTS" },
  { name: "OYUGIS LAW COURTS" },
  { name: "PORT VICTORIA LAW COURTS" },
  { name: "RONGO LAW COURTS" },
  { name: "RUIRU LAW COURTS" },
  { name: "RUMURUTI LAW COURTS" },
  { name: "RUNYENJES LAW COURTS" },
  { name: "SHANZU LAW COURTS" },
  { name: "SIAKAGO LAW COURTS" },
  { name: "SIAYA HIGH COURT" },
  { name: "SIAYA LAW COURTS" },
  { name: "SIRISIA LAW COURTS" },
  { name: "SOTIK LAW COURTS" },
  { name: "TAMU LAW COURTS" },
  { name: "TAVETA LAW COURTS" },
  { name: "TAWA LAW COURTS" },
  { name: "THIKA HIGH COURT" },
  { name: "THIKA LAW COURTS" },

  { name: "TIGANIA LAW COURTS" },
  { name: "TINDERET LAW COURTS" },
  { name: "TONONOKA CHILDREN’S COURT" },
  { name: "UKWALA LAW COURTS" },
  { name: "VIHIGA HIGH COURT" },
  { name: "VIHIGA LAW COURTS" },
  { name: "VOI HIGH COURT" },
  { name: "VOI LAW COURTS" },
  { name: "WAJIR LAW COURTS" },
  { name: "WAMUNYU LAW COURTS" },
  { name: "WANG’URU LAW COURTS" },
  { name: "WEBUYE LAW COURTS" },
  { name: "WINAM LAW COURTS" },
  { name: "WUNDANYI LAW COURTS" },
  { name: "MAKUENI LAW COURTS" },
  { name: "KIGUMO LAW COURTS" },
  { name: "MOMBASA KADHI COURT" },
  { name: "UPPERHILL KADHI COURT" },
  { name: "GARBATULLA KADHI COURT" },
  { name: "HABASWEIN KADHI COURT" },
  { name: "MODOGASHE KADHI COURT" },
  { name: "BURA/FAFI KADHI COURT" },
  { name: "BALAMBALA KADHI COURT" },
  { name: "TAKABA KADHI COURT" },

  { name: "MERTI KADHI COURT" },
  { name: "BUTE KADHI COURT" },
  { name: "ELDAS KADHI COURT" },
  { name: "IJARA KADHI COURT" },
  { name: "ELWAK KADHI COURT" },
  { name: "WITU KADHI COURT" },
  { name: "KILIFI LAW COURT" },
  { name: "WANG'URU LAW COURT" },
  { name: "NAIROBI KADHIS COURT" },
  { name: "HOLA KADHIS COURT" },
  { name: "MOTOMO LAW COURT" },
  { name: "KEITH LAW COURT" },
];





