import { CourtLevel } from "./models/court.model"; // if you use enums

export interface IOldCourt {
  name: string;
  level: CourtLevel;
  code?: string;
  magistrate?: string;
  primaryEmail?: string;
  secondaryEmails?: string[];
  phone?: string;
  location?: string; // ← add this
}

export const oldCourts: IOldCourt[] = [
  {
    name: "BARICHO LAW COURTS",
    level: CourtLevel.LAW_COURTS,
    magistrate: "HON. DAVID IRERI",
    phone: "+254724398698",
    primaryEmail: "barichocourt@court.go.ke",
    secondaryEmails: ["david.muchangi@court.go.ke"],
    code: "",
    location: "",
  },
  {
    name: "BOMET HIGH COURT",
    level: CourtLevel.HIGH_COURT,
    magistrate: "",
    phone: "",
    primaryEmail: "bomethighcourt@court.go.ke",
    secondaryEmails: ["martinrab2000@yahoo.co.uk", "martin.rabera@court.go.ke"],
    code: "",
    location: "",
  },
  {
    name: "BOMET LAW COURTS",
    level: CourtLevel.LAW_COURTS,
    magistrate: "HON. ESTHER BOKE",
    phone: "+254722578571",
    primaryEmail: "bometcourt@court.go.ke",
    secondaryEmails: ["esther.boke@court.go.ke"],
    code: "",
    location: "",
  },
  {
    name: "BONDO LAW COURTS",
    level: CourtLevel.LAW_COURTS,
    magistrate: "HON. DOUGLAS OGOTI",
    phone: "+254711698738",
    primaryEmail: "bondocourt@court.go.ke",
    secondaryEmails: ["douglas.ogoti@court.go.ke"],
    code: "",
    location: "",
  },
  {
    name: "BUNGOMA HIGH COURT",
    level: CourtLevel.HIGH_COURT,
    magistrate: "",
    phone: "",
    primaryEmail: "bungomahighcourt@court.go.ke",
    secondaryEmails: ["timothy.kiprono@court.go.ke"],
    code: "",
    location: "",
  },
  {
    name: "BUNGOMA LAW COURTS",
    level: CourtLevel.LAW_COURTS,
    magistrate: "HON. JOSEPHAT WAITITU GICHIMU",
    phone: "+254721795567",
    primaryEmail: "bungomacourt@court.go.ke",
    secondaryEmails: ["josphat.waititu@court.go.ke"],
    code: "",
    location: "",
  },
  {
  name: "BUSIA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "busiacourt@court.go.ke",
  secondaryEmails: ["kassim.akida@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "BUSIA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EDNA A.A. NYALOTI",
  phone: "+254721925156",
  primaryEmail: "busiacourt@court.go.ke",
  secondaryEmails: ["edna.nyaloti@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "BUTALI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. KIPNG’ENO REUBEN S. AKA SANG",
  phone: "+254729509643",
  primaryEmail: "butalicourt@court.go.ke",
  secondaryEmails: ["reuben.kipngeno@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "BUTERE LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EDWIN W. NYONGESA",
  phone: "+254721944965",
  primaryEmail: "buterecourt@court.go.ke",
  secondaryEmails: ["edwin.nyongesa@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "CHUKA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "chukahighcourt@court.go.ke",
  secondaryEmails: [
    "hminonda@yahoo.com",
    "herbert.mwendwa@court.go.ke",
  ],
  code: "",
  location: "",
},
{
  name: "CHUKA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JOYCE MKAMBE GANDANI",
  phone: "+254725852185",
  primaryEmail: "chukacourt.go.ke",
  secondaryEmails: ["jgandani@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "DADAAB LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EVANS MULEKA",
  phone: "+254720733399",
  primaryEmail: "dadaabcourt@court.go.ke",
  secondaryEmails: ["evans.muleka@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "DAGORETTI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. PAULINE MBULIKAH",
  phone: "+254722437296",
  primaryEmail: "dagoretticourt@court.go.ke",
  secondaryEmails: ["pauline.mbulikah@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "ELDAMA – RAVINE LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. RICHARD KOECH",
  phone: "+254722561433",
  primaryEmail: "eldamacourt@court.go.ke",
  secondaryEmails: ["richard.koech@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "ELDAMA RAVINE HIGH COURT (SUB-REGISTRY)",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "eldamacourt@court.go.ke",
  secondaryEmails: ["wilson.kitur@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "ELDORET HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "eldorethighcourt@court.go.ke",
  secondaryEmails: ["caroline.wattimah@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "ELDORET LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. DENNIS MIKOYAN",
  phone: "+254733329375",
  primaryEmail: "eldoretcourt.go.ke",
  secondaryEmails: ["dmikoyan@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "EMBU HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "embuhighcourt@court.go.ke",
  secondaryEmails: [
    "denchep@gmail.com",
    "dorcas.endoo@court.go.ke",
  ],
  code: "",
  location: "",
},
{
  name: "EMBU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. FRANCIS KYAMBIA",
  phone: "+254722610842",
  primaryEmail: "embucourt@court.go.ke",
  secondaryEmails: ["francis.kyambia@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "ENGINEER LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. HARRISON ADIKA",
  phone: "+254736437263",
  primaryEmail: "engineercourt@court.go.ke",
  secondaryEmails: ["harrison.adika@court.go.ke"],
  code: "",
  location: "",
},

  {
  name: "ETAGO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. VINCENT MUGENDI NYAGA",
  phone: "+254724866619",
  primaryEmail: "etagocourt@court.go.ke",
  secondaryEmails: ["vincent.nyaga@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "GARISSA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "garissahighcourt@court.go.ke",
  secondaryEmails: ["shadrackotuke@gmail.com", "shadrack.otuke@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "GARISSA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. THOMAS MURAGURI",
  phone: "+254711996755",
  primaryEmail: "garissacourt.go.ke",
  secondaryEmails: ["tmuraguri@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "GARSEN HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "garsenhighcourt@court.go.ke",
  secondaryEmails: ["oscar.wakina@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "GATUNDU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. DANIEL NG’ALU",
  phone: "+254722653257",
  primaryEmail: "gatunducourt@court.go.ke",
  secondaryEmails: ["daniel.ngalu@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "GICHUGU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MONICA MUNYENDO",
  phone: "+254726778046",
  primaryEmail: "gichugucourt@court.go.ke",
  secondaryEmails: ["monica.munyendo@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "GITHONGO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EDWIN MURIUKI",
  phone: "+254720751741",
  primaryEmail: "githongocourt@court.go.ke",
  secondaryEmails: ["edwin.nyagah@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "GITHUNGURI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. PETER MUHOLI",
  phone: "+254733474839",
  primaryEmail: "githunguricourt@court.go.ke",
  secondaryEmails: ["peter.muholi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "HAMISI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. NICODEMUS NYAMWEGA MOSETI",
  phone: "+254728996789",
  primaryEmail: "hamisicourt@court.go.ke",
  secondaryEmails: ["nicodemus.moseti@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "HOMABAY HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "homabayhighcourt@court.go.ke",
  secondaryEmails: ["christine.auka@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "HOMABAY LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JACINTA ORWA",
  phone: "+254719392343",
  primaryEmail: "homabaycourt@court.go.ke",
  secondaryEmails: ["jorwa@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "ISIOLO HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "isiolohighcourt@court.go.ke",
  secondaryEmails: [
    "maureen.odhiambo@court.go.ke",
    "odhiambomaureen87@gmail.com",
  ],
  code: "",
  location: "",
},
{
  name: "ISIOLO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. LUCY MUTAI",
  phone: "+254722331342",
  primaryEmail: "isiolocourt@court.go.ke",
  secondaryEmails: ["lucy.mutai@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "ITEN HIGH COURT (SUB-REGISTRY)",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "itencourt@court.go.ke",
  secondaryEmails: [
    "virginiawambui470@gmail.com",
    "virginia.wambui@court.go.ke",
  ],
  code: "",
  location: "",
},

  {
  name: "ITEN LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. GLADYS ADHIAMBO",
  phone: "+254721579766",
  primaryEmail: "itencourt@court.go.ke",
  secondaryEmails: ["gladys.adhiambo@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "JKIA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ANGELA NJERI THUKU",
  phone: "+254734488335",
  primaryEmail: "jkiacourt@court.go.ke",
  secondaryEmails: ["njeri.thuku@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KABARNET HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kabarnethighcourt@court.go.ke",
  secondaryEmails: ["crateya@gmail.com", "caroline.ateya@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KABARNET LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. PURITY CHEPKORIR KOSKEY",
  phone: "+254725856678",
  primaryEmail: "kabarnetcourt@court.go.ke",
  secondaryEmails: ["purity.koskey@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KABIYET LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. BRENDA BARTOO",
  phone: "+254722217527",
  primaryEmail: "kabiyetcourt@court.go.ke",
  secondaryEmails: ["brenda.bartoo@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAHAWA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. BOAZ MAURA OMBEWA",
  phone: "+254725474757",
  primaryEmail: "kahawacourt@court.go.ke",
  secondaryEmails: ["boaz.ombewa@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAJIADO HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kajiadohighcourt@court.go.ke",
  secondaryEmails: ["vicky.kachuodho@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAJIADO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ROSELYNE OGANYO",
  phone: "+254725233571",
  primaryEmail: "kajiadocourt@court.go.ke",
  secondaryEmails: ["roselyne.oganyo@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAKAMEGA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kakamegahighcourt@court.go.ke",
  secondaryEmails: ["jjmasiga@gmail.com", "james.masiga@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAKAMEGA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. PHILIP MUTUA",
  phone: "+254724586183",
  primaryEmail: "kakamegacourt@court.go.ke",
  secondaryEmails: ["philip.mutua@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAKUMA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. CHARLES MAYAMBA",
  phone: "+254727403600",
  primaryEmail: "kakumacourt@court.go.ke",
  secondaryEmails: ["charles.mayamba@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KALOLENI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. RITAH AMWAYI",
  phone: "+254707173984",
  primaryEmail: "kalolenicourt@court.go.ke",
  secondaryEmails: ["ritah.amwayi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAMWANGI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. NGUMI WANGECI",
  phone: "+254720955541",
  primaryEmail: "kamwangicourt@court.go.ke",
  secondaryEmails: ["wangechi.ngumi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KANDARA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EVA WANJIKU WAMBUGU",
  phone: "+254721569083",
  primaryEmail: "kandaracourt@court.go.ke",
  secondaryEmails: ["eva.wambugu@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KANGEMA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MARTIN MUTEGI",
  phone: "+254722957971",
  primaryEmail: "kangemacourt@court.go.ke",
  secondaryEmails: ["martin.kinyua@court.go.ke"],
  code: "",
  location: "",
},

 {
  name: "KANGUNDO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. SAMMY OPANDE",
  phone: "+254721151719",
  primaryEmail: "kangundocourt@court.go.ke",
  secondaryEmails: ["sammy.opande@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAPENGURIA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kapenguriahighcourt@court.go.ke",
  secondaryEmails: ["chelagatkenei@gmail.com", "nelly.kenei@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAPENGURIA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. STELLA TELEWA",
  phone: "+254704505502",
  primaryEmail: "kapenguriacourt@court.go.ke",
  secondaryEmails: ["stella.telewa@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAPSABET HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kapsabethighcourt@court.go.ke",
  secondaryEmails: ["john.aringo@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KAPSABET LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. KIBET SAMBU",
  phone: "+254722244961",
  primaryEmail: "kapsabetcourt@court.go.ke",
  secondaryEmails: ["kibet.sambu@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KARATINA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EVA KANYIRI KAIMENYI",
  phone: "+254721668737",
  primaryEmail: "karatinacourt@court.go.ke",
  secondaryEmails: ["eva.kanyiri@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KEHANCHA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MOSES OBIERO",
  phone: "+254728754336",
  primaryEmail: "kehanchacourt@court.go.ke",
  secondaryEmails: ["moses.obiero@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KENDU BAY LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EZEKIEL OBINA",
  phone: "+254722732416",
  primaryEmail: "kenducourt@court.go.ke",
  secondaryEmails: ["ezekiel.obina@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KENOL LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. SHEILA NYAGA",
  phone: "+254724747182",
  primaryEmail: "kenolcourt@court.go.ke",
  secondaryEmails: ["sheila.nyaga@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KERICHO HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kerichohighcourt@court.go.ke",
  secondaryEmails: ["felistus.okola@court.go.ke", "felazfelicia@yahoo.com"],
  code: "",
  location: "",
},
{
  name: "KERICHO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. TITO GESORA",
  phone: "+254722504211",
  primaryEmail: "kerichocourt@court.go.ke",
  secondaryEmails: ["tito.gesora@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KEROKA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EUNICE NYUTU",
  phone: "+254722137041",
  primaryEmail: "kerokacourt@court.go.ke",
  secondaryEmails: ["eunice.nyutu@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KERUGOYA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "",
  secondaryEmails: ["claire_nanjala@yahoo.co.uk"],
  code: "",
  location: "",
},
{
  name: "KERUGOYA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MARTHA W. MUTUKU",
  phone: "+254722337250",
  primaryEmail: "kerugoyacourt@court.go.ke",
  secondaryEmails: ["martha.mutuku@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KIAMBU HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kiambuhighcourt@court.go.ke",
  secondaryEmails: ["Karani.de@gmail.com", "Jacqueline.karani@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KIAMBU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ALFRED KIBIRU",
  phone: "+254722897428",
  primaryEmail: "kiambucourt@court.go.ke",
  secondaryEmails: ["alfred.kibiru@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KIBERA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "",
  secondaryEmails: ["deechebetmutai@gmail.com"],
  code: "",
  location: "",
},
{
  name: "KIBERA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ANNE MWANGI",
  phone: "+254724638096",
  primaryEmail: "kiberacourt@court.go.ke",
  secondaryEmails: ["anne.mwangi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KIGUMO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JOAN IRURA",
  phone: "+254723286958",
  primaryEmail: "kigumocourt.go.ke",
  secondaryEmails: ["jirura@court.go.ke"],
  code: "",
  location: "",
},

  {
  name: "KIKUYU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. LIZA LYNNE GICHEHA",
  phone: "+254720650894",
  primaryEmail: "kikuyucourt@court.go.ke",
  secondaryEmails: ["liza.gicheha@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KILGORIS HIGH COURT (SUB-REGISTRY)",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kilgoriscourt@court.go.ke",
  secondaryEmails: ["cypwaff@gmail.com", "cyprian.waswa@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KILGORIS LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MARY IMMACULATE GWARO",
  phone: "+254722233469",
  primaryEmail: "kilgoriscourt@court.go.ke",
  secondaryEmails: ["mary.moranga@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KILUNGU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. CAROLINE KEMEI",
  phone: "+254795056287",
  primaryEmail: "kilungucourt@court.go.ke",
  secondaryEmails: ["caroline.kemei@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KIMILILI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JOHN P. NANDI",
  phone: "+254724530684",
  primaryEmail: "kimililicourt@court.go.ke",
  secondaryEmails: ["paul.nandi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KISII HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kisiihighcourt@court.go.ke",
  secondaryEmails: ["winnie.keter@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KISII LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. STELLA N. ABUYA",
  phone: "+254733809346",
  primaryEmail: "kisiicourt@court.go.ke",
  secondaryEmails: ["stella.nabwire@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KISUMU HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kisumuhighcourt@court.go.ke",
  secondaryEmails: ["gloriah.nasimiyu@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KISUMU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. DICKSON ONYANGO",
  phone: "+254722763831",
  primaryEmail: "kisumucourt@court.go.ke",
  secondaryEmails: ["dickson.onyango@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KITALE HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "",
  secondaryEmails: ["margaret.makokha@court.go.ke", "makokha.nafula@yahoo.com"],
  code: "",
  location: "",
},
{
  name: "KITALE LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. SAMUEL MOKUA",
  phone: "+254722357463",
  primaryEmail: "kitalecourt@court.go.ke",
  secondaryEmails: ["ssmokua@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KITHIMANI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. HELLEN ONKWANI",
  phone: "+254720949582",
  primaryEmail: "kithimanicourt@court.go.ke",
  secondaryEmails: ["hellen.onkwani@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KITUI HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kituihighcourt@court.go.ke",
  secondaryEmails: ["elizabeth.karani@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KITUI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. DAVID MBURU",
  phone: "+254721611261",
  primaryEmail: "kituicourt.go.ke",
  secondaryEmails: ["dmburu@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KWALE HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "kwalehighcourt@court.go.ke",
  secondaryEmails: ["ruth.ogolla@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KWALE LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. LILIAN TSUMA LEWA",
  phone: "+254722992730",
  primaryEmail: "kwalecourt@court.go.ke",
  secondaryEmails: ["lilian.tsuma@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "KYUSO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. PAUL MAYOVA",
  phone: "+254724787329",
  primaryEmail: "kyusocourt@court.go.ke",
  secondaryEmails: ["paul.mayova@court.go.ke"],
  code: "",
  location: "",
},

 {
  name: "LAMU LAW COURT",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. PETER WASIKE",
  phone: "",
  primaryEmail: "lamucourt@court.go.ke",
  secondaryEmails: ["peter.wasike@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "LAMU HIGH COURT (SUB-REGISTRY)",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "lamucourt@court.go.ke",
  secondaryEmails: ["flavian.mulama@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "LIMURU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JARED MAGORI",
  phone: "+254726563011",
  primaryEmail: "limurucourt@court.go.ke",
  secondaryEmails: ["jared.magori@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "LODWAR HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "lodwarhighcourt@court.go.ke",
  secondaryEmails: ["neroidagwa@gmail.com", "nerolyne.idagwa@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "LODWAR LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EVANSON NGIGI",
  phone: "+254720700398",
  primaryEmail: "lodwarcourt@court.go.ke",
  secondaryEmails: ["evanson.ngigi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "LOITOKTOK LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ESTHER KIMILU",
  phone: "+254725503717",
  primaryEmail: "loitoktokcourt@court.go.ke",
  secondaryEmails: ["esther.kimilu@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MACHAKOS HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "machakoshighcourt@court.go.ke",
  secondaryEmails: ["mercy.thibaru@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MACHAKOS LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. CHARITY CHEBII OLUOCH",
  phone: "+254722809874",
  primaryEmail: "machakoscourt@court.go.ke",
  secondaryEmails: ["charity.oluoch@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MACHAKOS KADHIS COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "machakoscourt@court.go.ke",
  secondaryEmails: ["charity.oluoch@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MADIANY LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ERIC KIDALI",
  phone: "+254731308326",
  primaryEmail: "madianycourt@court.go.ke",
  secondaryEmails: ["eric.malesi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MAKADARA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "",
  secondaryEmails: ["stephany.wambui@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MAKADARA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. KENNEDY BIDALI",
  phone: "+254722744358",
  primaryEmail: "makadaracourt@court.go.ke",
  secondaryEmails: ["kbidali@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MAKINDU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. YUSUF SHIKANDA",
  phone: "+254735420523",
  primaryEmail: "makinducourt@court.go.ke",
  secondaryEmails: ["yusuf.shikanda@court.go.ke"],
  code: "52112",
  location: "",
},
{
  name: "MAKUENI HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "makuenihighcourt@court.go.ke",
  secondaryEmails: ["fransisca.chepkoech@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MAKUENI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. PETER GESORA",
  phone: "+254722801555",
  primaryEmail: "makuenicourt.go.ke",
  secondaryEmails: ["pgesora@court.go.ke"],
  code: "34067",
  location: "",
},
{
  name: "MALABA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. OCHARO MOMANYI",
  phone: "+254712224111",
  primaryEmail: "malabacourt@court.go.ke",
  secondaryEmails: ["ocharo.momanyi@court.go.ke"],
  code: "66179",
  location: "",
},
{
  name: "MALINDI HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "malindihighcourt@court.go.ke",
  secondaryEmails: ["mwendenzau12@gmail.com"],
  code: "",
  location: "",
},
{
  name: "MALINDI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ELIZABETH USUI",
  phone: "+254723925898",
  primaryEmail: "malindicourt.go.ke",
  secondaryEmails: ["eusui@court.go.ke"],
  code: "39910",
  location: "",
},
{
  name: "MANDERA HIGH COURT (SUB-REGISTRY)",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "manderacourt@court.go.ke",
  secondaryEmails: ["cornelomondi@ymail.com", "cornel.omondi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MANDERA LAW COURT",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. BENSON KHAPOYA",
  phone: "+254723691626",
  primaryEmail: "manderacourt@court.go.ke",
  secondaryEmails: ["benson.khapoya@court.go.ke"],
  code: "52536",
  location: "",
},

 {
  name: "MARALAL HIGH COURT (SUB-REGISTRY)",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "maralalcourt@court.go.ke",
  secondaryEmails: ["victor.asiyo@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MARALAL LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ALLAN TEMBA SITATI",
  phone: "+254715493762",
  primaryEmail: "maralalcourt@court.go.ke",
  secondaryEmails: ["temba.sitati@court.go.ke"],
  code: "51768",
  location: "",
},
{
  name: "MARIAKANI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. SIMON KIMANI MBURU",
  phone: "+254721880842",
  primaryEmail: "mariakanicourt@court.go.ke",
  secondaryEmails: ["simon.mburu@court.go.ke"],
  code: "57853",
  location: "",
},
{
  name: "MARIMANTI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. TOM WAFULA MBAYAKI",
  phone: "+254725089412",
  primaryEmail: "marimanticourt@court.go.ke",
  secondaryEmails: ["tom.wafula@court.go.ke"],
  code: "63058",
  location: "",
},
{
  name: "MARSABIT HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "marsabithighcourt@court.go.ke",
  secondaryEmails: ["aromesk@gmail.com", "simon.kaigongi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MARSABIT LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. CHRISTINE WEKESA MULONGO",
  phone: "+254724500947",
  primaryEmail: "marsabitcourt@court.go.ke",
  secondaryEmails: ["christine.wekesa@court.go.ke"],
  code: "52120",
  location: "",
},
{
  name: "MASENO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MELANIE CELESTINE A. AWINO",
  phone: "+254721479832",
  primaryEmail: "masenocourt@court.go.ke",
  secondaryEmails: ["melanie.ochieng@court.go.ke"],
  code: "53516",
  location: "",
},
{
  name: "MAUA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. FELIX KOMBO",
  phone: "+254722327819",
  primaryEmail: "mauacourt.go.ke",
  secondaryEmails: ["fkombo@court.go.ke"],
  code: "39863",
  location: "",
},
{
  name: "MAVOKO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. BARBARA OJOO",
  phone: "+254711700999",
  primaryEmail: "mavokocourt.go.ke",
  secondaryEmails: ["bojoo@court.go.ke"],
  code: "34130",
  location: "",
},
{
  name: "MBITA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MARTHA AGUTU",
  phone: "+254713748106",
  primaryEmail: "mbitacourt@court.go.ke",
  secondaryEmails: ["martha.agutu@court.go.ke"],
  code: "57714",
  location: "",
},
{
  name: "MERU HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "meruhighcourt@gmail.com",
  secondaryEmails: ["susan.ndegwa@court.go.ke", "ssusangungi@gmail.com"],
  code: "",
  location: "",
},
{
  name: "MERU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. BENJAMIN MITULLAH",
  phone: "+254738527506",
  primaryEmail: "merucourt.go.ke",
  secondaryEmails: ["bmitullah@court.go.ke"],
  code: "40296",
  location: "",
},
{
  name: "MIGORI HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "migorihighcourt@court.go.ke",
  secondaryEmails: ["amunyuny@gmail.com", "angela.munyuny@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MIGORI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. NAOMI WAIRIMU",
  phone: "+254734214433",
  primaryEmail: "migoricourt@court.go.ke",
  secondaryEmails: ["naomi.wairimu@court.go.ke"],
  code: "49876",
  location: "",
},
{
  name: "NAIROBI CHIEF MAGISTRATES COURT",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EVERLYNE OLWANDE",
  phone: "+254733729261",
  primaryEmail: "milimani.cmfamily@court.go.ke",
  secondaryEmails: ["eolwande@court.go.ke"],
  code: "40563",
  location: "",
},
{
  name: "MILIMANI H.C FAMILY DIVISION",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "milimani.family@court.go.ke",
  secondaryEmails: ["albert.lesootia@court.go.ke", "lesootiala@gmail.com"],
  code: "",
  location: "",
},
{
  name: "MOIBEN LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. BARNABAS KIPTOO",
  phone: "+254722968350",
  primaryEmail: "moibencourt@court.go.ke",
  secondaryEmails: ["barnabas.kiptoo@court.go.ke"],
  code: "62719",
  location: "",
},

 {
  name: "MOLO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. CAROLYNE OCHARO",
  phone: "+254717627373",
  primaryEmail: "molocourt.go.ke",
  secondaryEmails: ["cocharo@court.go.ke"],
  code: "40173",
  location: "",
},
{
  name: "MOMBASA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "mombasahighcourt@court.go.ke",
  secondaryEmails: ["green.opiyo@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MOMBASA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ALEX ITHUKU",
  phone: "+254701399691",
  primaryEmail: "mombasacourt.go.ke",
  secondaryEmails: ["aithuku@court.go.ke"],
  code: "39944",
  location: "",
},
{
  name: "MOYALE LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. WILLY KIPKOECH CHERUIYOT",
  phone: "+254721961400",
  primaryEmail: "moyalecourt@court.go.ke",
  secondaryEmails: ["willy.cheruiyot@court.go.ke"],
  code: "52269",
  location: "",
},
{
  name: "MSAMBWENI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. LEAH WANDIA KABARIA",
  phone: "+254727722158",
  primaryEmail: "msambwenicourt@court.go.ke",
  secondaryEmails: ["leah.kabaria@court.go.ke"],
  code: "58192",
  location: "",
},
{
  name: "MUKURWEINI LAW COURT",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EDDAH AGADE",
  phone: "+254728171042",
  primaryEmail: "mukurweinicourt@court.go.ke",
  secondaryEmails: ["agade.savai@court.go.ke"],
  code: "57586",
  location: "",
},
{
  name: "MUMIAS LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. THOMAS OBUTU ATANGA",
  phone: "+254722268019",
  primaryEmail: "mumiascourt@court.go.ke",
  secondaryEmails: ["thomas.obutu@court.go.ke"],
  code: "40521",
  location: "",
},
{
  name: "MURANG’A LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. PETER NDWIGA",
  phone: "+254720806228",
  primaryEmail: "murangacourt@court.go.ke",
  secondaryEmails: ["pndwiga@court.go.ke"],
  code: "40505",
  location: "",
},
{
  name: "MURANG’A HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "murangahighcourt@court.go.ke",
  secondaryEmails: ["emusambai@gmail.com", "eric.musambai@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "MUTOMO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MERCY N. WANYAMA",
  phone: "+254723064222",
  primaryEmail: "mutomocourt@court.go.ke",
  secondaryEmails: ["mercy.nasimiyu@court.go.ke"],
  code: "57405",
  location: "",
},
{
  name: "MWINGI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MWANGI K. MWANGI",
  phone: "+254721962511",
  primaryEmail: "mwingicourt.go.ke",
  secondaryEmails: ["kmwangi@court.go.ke"],
  code: "40026",
  location: "",
},
{
  name: "NAIVASHA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "naivashahighcourt@court.go.ke",
  secondaryEmails: ["jkabugo@gmail.com", "juliana.ndengeri@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "NAIVASHA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. NATHAN LUTTA",
  phone: "+254720915875",
  primaryEmail: "naivashacourt@court.go.ke",
  secondaryEmails: ["nlutta@court.go.ke"],
  code: "38875",
  location: "",
},
{
  name: "NAKURU HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "nakuruhighcourt@court.go.ke",
  secondaryEmails: ["christinemenya@yahoo.com", "christine.menya@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "NAKURU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ELIZABETH JUMA",
  phone: "+254722994272",
  primaryEmail: "nakurucourt@court.go.ke",
  secondaryEmails: ["elizabeth.juma@court.go.ke"],
  code: "39839",
  location: "",
},
{
  name: "NANYUKI HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "nanyukihighcourt@court.go.ke",
  secondaryEmails: ["maureen.mumbi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "NANYUKI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ANGELO KITHINJI RWITO",
  phone: "+254722417945",
  primaryEmail: "nanyukicourt@court.go.ke",
  secondaryEmails: ["angelo.rwito@court.go.ke"],
  code: "40539",
  location: "",
},
{
  name: "NAROK HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "narokhighcourt@court.go.ke",
  secondaryEmails: ["phylis.shinyada@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "NAROK LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. HEZRON M. NYABERI",
  phone: "+254721242626",
  primaryEmail: "narokcourt@court.go.ke",
  secondaryEmails: ["hezron.nyaberi@court.go.ke"],
  code: "39847",
  location: "",
},
{
  name: "NDHIWA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EVERLYNE M. ONZERE",
  phone: "+254721305257",
  primaryEmail: "ndhiwacourt@court.go.ke",
  secondaryEmails: ["everlyne.onzere@court.go.ke"],
  code: "57625",
  location: "",
},
{
  name: "NGONG LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. CHARLES A. KUTWA",
  phone: "+254722306996",
  primaryEmail: "ngongcourt@court.go.ke",
  secondaryEmails: ["charles.kutwa@court.go.ke"],
  code: "43375",
  location: "",
},
{
  name: "NKUBU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. SOLOMON NG'ETICH",
  phone: "+254721102536",
  primaryEmail: "nkubucourt@court.go.ke",
  secondaryEmails: ["solomon.ngetich@court.go.ke"],
  code: "51962",
  location: "",
},
{
  name: "NYAHURURU HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "",
  secondaryEmails: ["fredrick.larabi@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "NYAHURURU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EVANS H. KEAGO",
  phone: "+254726504803",
  primaryEmail: "nyahururucourt@court.go.ke",
  secondaryEmails: ["hezekiah.keago@court.go.ke"],
  code: "39871",
  location: "",
},

  {
  name: "NYAMIRA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "nyamirahighcourt@court.go.ke",
  secondaryEmails: ["beryl.jumar@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "NYAMIRA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. BERNARD OCHIENG",
  phone: "+254735467541",
  primaryEmail: "nyamiracourt@court.go.ke",
  secondaryEmails: ["bernard.ochieng@court.go.ke"],
  code: "38914",
  location: "",
},
{
  name: "NYANDARUA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "nyandaruahighcourt@court.go.ke",
  secondaryEmails: ["atamba.mwera@court.go.ke", "mweralynn@gmail.com"],
  code: "",
  location: "",
},
{
  name: "NYANDO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. LILIAN NAFULA KINIALE",
  phone: "+254711296133",
  primaryEmail: "nyandocourt@court.go.ke",
  secondaryEmails: ["lilian.nafula@court.go.ke"],
  code: "52081",
  location: "",
},
{
  name: "NYERI HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "nyerihighcourt@court.go.ke",
  secondaryEmails: ["charity.kipkorir@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "NYERI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ELENA G. NDERITU",
  phone: "+254724020575",
  primaryEmail: "nyericourt@court.go.ke",
  secondaryEmails: ["elena.nderitu@court.go.ke"],
  code: "40547",
  location: "",
},
{
  name: "OGEMBO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. PAUL BIWOTT",
  phone: "+254722440200",
  primaryEmail: "ogembocourt@court.go.ke",
  secondaryEmails: ["pbiwot@court.go.ke"],
  code: "33118",
  location: "",
},
{
  name: "OL KALOU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JUDICASTER NTHAMBI NTHUKU",
  phone: "+254721463420",
  primaryEmail: "olcourt@court.go.ke",
  secondaryEmails: ["judicaster.nthuku@court.go.ke"],
  code: "52552",
  location: "",
},
{
  name: "OTHAYA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. SANDRA OGOT",
  phone: "+254722813941",
  primaryEmail: "othayacourt@court.go.ke",
  secondaryEmails: ["sandra.ogot@court.go.ke"],
  code: "57706",
  location: "",
},
{
  name: "OYUGIS LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. SAMSON OMWENGA",
  phone: "+254723549128",
  primaryEmail: "oyugiscourt@court.go.ke",
  secondaryEmails: ["samson.omwenga@court.go.ke"],
  code: "41917",
  location: "",
},
{
  name: "PORT VICTORIA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ANNE KARIMI NJERU",
  phone: "+254711732391",
  primaryEmail: "portcourt@court.go.ke",
  secondaryEmails: ["anne.njeru@court.go.ke"],
  code: "80221",
  location: "",
},
{
  name: "RONGO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. CHRISPINE ORUO",
  phone: "+254721863036",
  primaryEmail: "rongocourt@court.go.ke",
  secondaryEmails: ["chrispine.oruo@court.go.ke"],
  code: "63040",
  location: "",
},
{
  name: "RUIRU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JOSEPH WERE",
  phone: "+254734992077",
  primaryEmail: "ruirucourt@court.go.ke",
  secondaryEmails: ["joseph.were@court.go.ke"],
  code: "33257",
  location: "",
},
{
  name: "RUMURUTI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MARTIN MAINA WACHIRA",
  phone: "+254723433082",
  primaryEmail: "rumuruticourt@court.go.ke",
  secondaryEmails: ["martin.wachira@court.go.ke"],
  code: "58338",
  location: "",
},
{
  name: "RUNYENJES LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. CATHERINE KISIANGANI",
  phone: "+254725822872",
  primaryEmail: "runyenjescourt@court.go.ke",
  secondaryEmails: ["kisiangani.khakasa@court.go.ke"],
  code: "62808",
  location: "",
},
{
  name: "SHANZU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ANTHONY MWICIGI",
  phone: "+254722322374",
  primaryEmail: "shanzucourt@court.go.ke",
  secondaryEmails: ["anthony.mwicigi@court.go.ke"],
  code: "40123",
  location: "",
},
{
  name: "SIAKAGO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. STEPHEN KALAI NGII",
  phone: "+254720322272",
  primaryEmail: "siakagocourt@court.go.ke",
  secondaryEmails: ["stephen.ngii@court.go.ke"],
  code: "57918",
  location: "",
},
{
  name: "SIAYA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "siayahighcourt@court.go.ke",
  secondaryEmails: ["benjamin.limo@court.go.ke"],
  code: "",
  location: "",
},

  {
  name: "SIAYA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MARGARET W. ONDITI",
  phone: "726160644",
  primaryEmail: "siayacourt@court.go.ke",
  secondaryEmails: ["margaret.onditi@court.go.ke"],
  code: "21690",
  location: "",
},
{
  name: "SIRISIA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. RAYMOND KIBET LANGAT",
  phone: "727734030",
  primaryEmail: "sirisiacourt@court.go.ke",
  secondaryEmails: ["raymond.langat@court.go.ke"],
  code: "57667",
  location: "",
},
{
  name: "SOTIK LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. BETHWEL K. MATATA",
  phone: "723217711",
  primaryEmail: "sotikcourt@court.go.ke",
  secondaryEmails: ["bethwel.matata@court.go.ke"],
  code: "52154",
  location: "",
},
{
  name: "TAMU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. AMOS MAKOROSS",
  phone: "790851891",
  primaryEmail: "tamucourt@court.go.ke",
  secondaryEmails: ["amos.kiprop@court.go.ke"],
  code: "51970",
  location: "",
},
{
  name: "TAVETA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. CECILIA KARIMI KITHINJI",
  phone: "721303887",
  primaryEmail: "tavetacourt@court.go.ke",
  secondaryEmails: ["kckarimi@court.go.ke"],
  code: "53312",
  location: "",
},
{
  name: "TAWA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. STEPHEN JALANG’O",
  phone: "721812270",
  primaryEmail: "tawacourt@court.go.ke",
  secondaryEmails: ["stephen.wadida@court.go.ke"],
  code: "52104",
  location: "",
},
{
  name: "THIKA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "thikahighcourt@court.go.ke",
  secondaryEmails: ["fredrick.imaana@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "THIKA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. STELLA B. ATAMBO",
  phone: "722370080",
  primaryEmail: "thikacourt@court.go.ke",
  secondaryEmails: ["stella.atambo@court.go.ke"],
  code: "40610",
  location: "",
},
{
  name: "TIGANIA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JAMES MACHARIA",
  phone: "722698140",
  primaryEmail: "tiganiacourt@court.go.ke",
  secondaryEmails: ["jmacharia@court.go.ke"],
  code: "43325",
  location: "",
},
{
  name: "TINDERET LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. BONFACE WACHIRA",
  phone: "721746651",
  primaryEmail: "tinderetcourt@court.go.ke",
  secondaryEmails: ["bonface.wachira@court.go.ke"],
  code: "80235",
  location: "",
},

{
  name: "UKWALA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EDWARD TSIMONJERO",
  phone: "723289306",
  primaryEmail: "ukwalacourt@court.go.ke",
  secondaryEmails: ["edward.tsimonjero@court.go.ke"],
  code: "80333",
  location: "",
},
{
  name: "VIHIGA HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "",
  secondaryEmails: ["omolloberyl@gmail.com"],
  code: "",
  location: "",
},
{
  name: "VIHIGA LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JACQUELINE AGONDA",
  phone: "721413607",
  primaryEmail: "vihigacourt@court.go.ke",
  secondaryEmails: ["jacqueline.agonda@court.go.ke"],
  code: "65929",
  location: "",
},
{
  name: "VOI HIGH COURT",
  level: CourtLevel.HIGH_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "",
  secondaryEmails: ["sinkiyian.tobiko@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "VOI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MILDRED OBURA",
  phone: "725090124",
  primaryEmail: "voicourt@court.go.ke",
  secondaryEmails: ["mildred.obura@court.go.ke"],
  code: "40937",
  location: "",
},
{
  name: "WAJIR LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ROSALYNN A. AGANYO",
  phone: "721207332",
  primaryEmail: "wajircourt@court.go.ke",
  secondaryEmails: ["rosalynn.aganyo@court.go.ke"],
  code: "57544",
  location: "",
},
{
  name: "WAMUNYU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. EUGENE PASCAL NABWANA",
  phone: "724100083",
  primaryEmail: "wamunyucourt@court.go.ke",
  secondaryEmails: ["eugene.nabwana@court.go.ke"],
  code: "80360",
  location: "",
},
{
  name: "WANG’URU LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. MARTHA OPANGA",
  phone: "722350997",
  primaryEmail: "wangurucourt@court.go.ke",
  secondaryEmails: ["martha.akoth@court.go.ke"],
  code: "52578",
  location: "",
},

{
  name: "WEBUYE LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. VIOLA JEPKORIR YATOR",
  phone: "723013901",
  primaryEmail: "webuyecourt@court.go.ke",
  secondaryEmails: ["viola.yator@court.go.ke"],
  code: "57227",
  location: "",
},
{
  name: "WINAM LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. ROBERT M. OANDA",
  phone: "729440444",
  primaryEmail: "winamcourt@court.go.ke",
  secondaryEmails: ["robert.oanda@court.go.ke"],
  code: "41844",
  location: "",
},
{
  name: "WUNDANYI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. DORCAS WANGECI MAITERI",
  phone: "721969978",
  primaryEmail: "wundanyicourt@court.go.ke",
  secondaryEmails: ["dorcas.maiteri@court.go.ke"],
  code: "52219",
  location: "",
},
{
  name: "MAKUENI LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "",
  phone: "0722801555",
  primaryEmail: "makuenicourt@court.go.ke",
  secondaryEmails: ["pgesora@court.go.ke"],
  code: "43067",
  location: "",
},
{
  name: "KIGUMO LAW COURTS",
  level: CourtLevel.LAW_COURTS,
  magistrate: "Hon. Joan Irura",
  phone: "0723286958",
  primaryEmail: "kigumocourt@court.go.ke",
  secondaryEmails: ["jirure@court.go.ke"],
  code: "49850",
  location: "",
},
{
  name: "MOMBASA KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. ABDIAZIZ MAALIM",
  phone: "+254718707778",
  primaryEmail: "abdiaziz.mohamed@court.go.ke",
  secondaryEmails: [],
  code: "61501",
  location: "MOMBASA",
},
{
  name: "UPPERHILL KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. SUKYAN OMAR",
  phone: "+254722943982",
  primaryEmail: "sukyan.omar@court.go.ke",
  secondaryEmails: [],
  code: "40301",
  location: "UPPERHILL",
},
{
  name: "GARBATULLA KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. DADACHA ALI IBRAHIM",
  phone: "+254703705838",
  primaryEmail: "ali.dadacha@court.go.ke",
  secondaryEmails: [],
  code: "65741",
  location: "GARBATULLA",
},
{
  name: "HABASWEIN KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. ADAN IBRAHIM TULLU",
  phone: "+254725486782",
  primaryEmail: "adan.tullu@court.go.ke",
  secondaryEmails: [],
  code: "61569",
  location: "HABASWEIN",
},
{
  name: "MODOGASHE KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "Under Mahakama Popote",
  phone: "",
  primaryEmail: "",
  secondaryEmails: [],
  code: "",
  location: "MODOGASHE",
},
{
  name: "BURA/FAFI KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "Under Mahakama Popote",
  phone: "",
  primaryEmail: "",
  secondaryEmails: [],
  code: "",
  location: "BURA/FAFI",
},
{
  name: "BALAMBALA KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. SAMBUL MOHAMED MUHIYIDIN",
  phone: "+254723649406",
  primaryEmail: "mohamed.sambul@court.go.ke",
  secondaryEmails: [],
  code: "65678",
  location: "BALAMBALA",
},
{
  name: "TAKABA KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. HUSSEIN MOHAMED HASSAN",
  phone: "+254720756635",
  primaryEmail: "mohamed.hussein@court.go.ke",
  secondaryEmails: [],
  code: "65733",
  location: "TAKABA",
},
{
  name: "MERTI KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. DOGO SHEIKH DABASOO",
  phone: "+254725634502",
  primaryEmail: "sheikh.dogo@court.go.ke",
  secondaryEmails: [],
  code: "65822",
  location: "MERTI",
},
{
  name: "BUTE KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. ISAAK HASSAN NOOR",
  phone: "+254715562012",
  primaryEmail: "isaack.noor@court.go.ke",
  secondaryEmails: [],
  code: "61624",
  location: "BUTE",
},
{
  name: "ELDAS KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. ABDI OSMAN SHEIKH",
  phone: "+254720877340",
  primaryEmail: "abdi.sheikh@court.go.ke",
  secondaryEmails: [],
  code: "61755",
  location: "ELDAS",
},
{
  name: "IJARA KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. RASHID KOKONYA OTUNDO",
  phone: "+254721847430",
  primaryEmail: "rashid.otundo@court.go.ke",
  secondaryEmails: [],
  code: "61789",
  location: "IJARA",
},
{
  name: "ELWAK KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. AHMED ISSACK MAALIM",
  phone: "+254722109207",
  primaryEmail: "issack.ahmed@court.go.ke",
  secondaryEmails: [],
  code: "65759",
  location: "ELWAK",
},
{
  name: "WITU KADHI COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "HON. MWAMBELE MOHAMED SULEIMAN",
  phone: "+254714747188",
  primaryEmail: "mohamed.mwambele@court.go.ke",
  secondaryEmails: [],
  code: "65806",
  location: "WITU",
},
{
  name: "KILIFI LAW COURT",
  level: CourtLevel.LAW_COURTS,
  magistrate: "HON. JAMES MWANIKI",
  phone: "",
  primaryEmail: "kilificourt@court.go.ke",
  secondaryEmails: ["j.mwaniki@court.go.ke"],
  code: "",
  location: "",
},
{
  name: "WANG'URU LAW COURT",
  level: CourtLevel.LAW_COURTS,
  magistrate: "",
  phone: "",
  primaryEmail: "wangurucourt@court.go.ke",
  secondaryEmails: [],
  code: "",
  location: "",
},
{
  name: "NAIROBI KADHIS COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "deputychiefkadhiscourt@court.go.ke",
  secondaryEmails: [],
  code: "",
  location: "",
},
{
  name: "HOLA KADHIS COURT",
  level: CourtLevel.KADHI_COURT,
  magistrate: "",
  phone: "",
  primaryEmail: "holacourt@court.go.ke",
  secondaryEmails: [],
  code: "",
  location: "",
},
{
  name: "MOTOMO LAW COURT",
  level: CourtLevel.LAW_COURTS,
  magistrate: "",
  phone: "",
  primaryEmail: "motomocourt@court.go.ke",
  secondaryEmails: [],
  code: "",
  location: "",
},

{
  name: "KEITH LAW COURT",
  level: CourtLevel.LAW_COURTS,
  magistrate: "",
  phone: "",
  primaryEmail: "denniskeith62@gmail.com",
  secondaryEmails: [],
  code: "",
  location: "",
},


];