/// <reference types="node" />
import mongoose from "mongoose";
import dotenv from "dotenv";
import Record, { Form60Compliance, StatusAtGP } from "./models/record.model";
import Court from "./models/court.model";

dotenv.config();

const MONGO_URI =
  process.env.MONGODB_URI ||
  process.env.MONGO_URI ||
  "mongodb://localhost:27017/orhc";
const DB_NAME = process.env.DB_NAME;

interface RawRecord {
  causeNo: string;
  nameOfDeceased: string;
  dateReceived: string;       // eCitizen date
  dateOfReceipt: string;      // registry receipt date
  dateForwardedToGP?: string;
  form60Compliance: Form60Compliance;
  statusAtGP: StatusAtGP;
  rejectionReason?: string;
  courtName: string;
}


// Date approximation policy (applied where eCitizen date is missing):
//   dateReceived ≈ dateOfReceipt − 5 days  (typical ~5-day forwarding cycle)

const RAW_RECORDS: RawRecord[] = [

 // ========================================================================
// PAGE 94 - GATUNDU, SIAYA LAW COURTS (continued)
// ========================================================================
{
  causeNo: "E310/2025",
  nameOfDeceased: "WAIRIMU KIHUHA",
  dateOfReceipt: "2026-01-08",
  dateReceived: "2025-10-24",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "GATUNDU LAW COURTS",
},
{
  causeNo: "E592/2025",
  nameOfDeceased: "WASHINGTONGE OKELLO MWALO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-22",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E591/2025",
  nameOfDeceased: "OBIERO ABANGE OGOT",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-20",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E590/2025",
  nameOfDeceased: "PETER OBIERO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-20",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},

// ========================================================================
// PAGE 95 - SIAYA, KIKUYU, SIAKAGO, ELDORET HIGH, WEBUYE, MOLO LAW COURTS
// ========================================================================
{
  causeNo: "E587/2025",
  nameOfDeceased: "GERSON ODEYO WAGA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-19",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E582/2025",
  nameOfDeceased: "LOMA ONDEGO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-15",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E581/2025",
  nameOfDeceased: "OTUOMA ADEDE",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-15",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E580/2025",
  nameOfDeceased: "WILLIAM JUMA AUMA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-15",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E579/2025",
  nameOfDeceased: "JOHN WAMBAYA WAGULA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-15",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E578/2025",
  nameOfDeceased: "KILION OWINIO RESA WINO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-15",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E577/2025",
  nameOfDeceased: "JANET OMBALO OWINIO JENET",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-15",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E569/2025",
  nameOfDeceased: "ZEDEIKAH WAUDY GODIAH ZEDEKIA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-17",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E529/2025",
  nameOfDeceased: "PANYAKO OKUMU",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-17",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E367/2025",
  nameOfDeceased: "MICHAEL KARIUKI WAKANJOYA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-09",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KIKUYU LAW COURTS",
},
{
  causeNo: "E290/2025",
  nameOfDeceased: "GEORGE NJOROGE WARUINGI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-24",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KIKUYU LAW COURTS",
},

// ========================================================================
// PAGE 96 - KIKUYU, SIAKAGO, ELDORET HIGH, WEBUYE LAW COURTS
// ========================================================================
{
  causeNo: "E193/2025",
  nameOfDeceased: "CHRISTOPHER MBUTHI NGUME",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-06-04",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KIKUYU LAW COURTS",
},
{
  causeNo: "E091/2025",
  nameOfDeceased: "GODFREY KIMACIA NJOROGE KIMACHIA GEOFFREY KIMANCHIA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-04-08",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KIKUYU LAW COURTS",
},
{
  causeNo: "E041/2025",
  nameOfDeceased: "KORINERIO NJUGUNA NJOROGE",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-02-19",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KIKUYU LAW COURTS",
},
{
  causeNo: "E040/2025",
  nameOfDeceased: "MUHUTA WAHWAI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-26",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KIKUYU LAW COURTS",
},
{
  causeNo: "E284/2025",
  nameOfDeceased: "NJERU CIARAGO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-22",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAKAGO LAW COURTS",
},
{
  causeNo: "E271/2025",
  nameOfDeceased: "IRERI NJERU",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-10",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAKAGO LAW COURTS",
},
{
  causeNo: "E267/2025",
  nameOfDeceased: "MURANGO MUKENIE",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-03",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAKAGO LAW COURTS",
},
{
  causeNo: "E265/2025",
  nameOfDeceased: "TITU NJUKI NJERU",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-26",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAKAGO LAW COURTS",
},
{
  causeNo: "E256/2025",
  nameOfDeceased: "NJUKI KIVINDU RWANDA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-19",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAKAGO LAW COURTS",
},
{
  causeNo: "E230/2025",
  nameOfDeceased: "PETER ARUSEI LEBOBOIN",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-16",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "ELDORET HIGH COURT",
},
{
  causeNo: "E007/2025",
  nameOfDeceased: "MANG'OLI WEKESA KOMBE",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-02-26",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "WEBUYE LAW COURTS",
},

// ========================================================================
// PAGE 97 - WEBUYE, MOLO, ELDAMA-RAVINE, KENOL, KILGORIS LAW COURTS
// ========================================================================
{
  causeNo: "E101/2025",
  nameOfDeceased: "PELLA MWANGI KIFWOLO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-23",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "WEBUYE LAW COURTS",
},
{
  causeNo: "E135/2025",
  nameOfDeceased: "NICKSON KIPYEGON NGETICH",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-04",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOLO LAW COURTS",
},
{
  causeNo: "E133/2025",
  nameOfDeceased: "CALEB MOSE OMOSA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-24",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOLO LAW COURTS",
},
{
  causeNo: "E127/2025",
  nameOfDeceased: "KIPTUM KEIYO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-10-31",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOLO LAW COURTS",
},
{
  causeNo: "E100/2025",
  nameOfDeceased: "JOHN KAMAU NJUGUNA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-09-17",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOLO LAW COURTS",
},
{
  causeNo: "E091/2025",
  nameOfDeceased: "DORCAS WAITHIRA KARIUKI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-10-21",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOLO LAW COURTS",
},
{
  causeNo: "E090/2025",
  nameOfDeceased: "EUNICE WAMBUI NJUGUNA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-24",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOLO LAW COURTS",
},
{
  causeNo: "E013/2025",
  nameOfDeceased: "WACEKE MWANGI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-05-06",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOLO LAW COURTS",
},
{
  causeNo: "E129/2025",
  nameOfDeceased: "CHEMJOR CHEMOR CHEMORO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-10",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "ELDAMA – RAVINE LAW COURTS",
},
{
  causeNo: "E128/2025",
  nameOfDeceased: "KIPLAGAT CHEMOR",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-10",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "ELDAMA – RAVINE LAW COURTS",
},
{
  causeNo: "E127/2025",
  nameOfDeceased: "IPSESEN CHEBET",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-09",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "ELDAMA – RAVINE LAW COURTS",
},

// ========================================================================
// PAGE 98 - ELDAMA-RAVINE, KENOL, KILGORIS, KERICHO HIGH, BOMET, NYANDO LAW COURTS
// ========================================================================
{
  causeNo: "E126/2025",
  nameOfDeceased: "CHEBOR AYABEI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-10",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "ELDAMA – RAVINE LAW COURTS",
},
{
  causeNo: "E181/2025",
  nameOfDeceased: "BENJAMIN KINYANJUI GATHU",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-03",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KENOL LAW COURTS",
},
{
  causeNo: "E171/2025",
  nameOfDeceased: "MUTHAMA MUNYAO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-17",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KENOL LAW COURTS",
},
{
  causeNo: "E170/2025",
  nameOfDeceased: "JULIUS MWITURIA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-21",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KENOL LAW COURTS",
},
{
  causeNo: "E158/2025",
  nameOfDeceased: "WAWERU NG'ANG'A",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-10-13",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KENOL LAW COURTS",
},
{
  causeNo: "E147/2025",
  nameOfDeceased: "NGANGA CHEGE",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-10-09",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KENOL LAW COURTS",
},
{
  causeNo: "E002/2025",
  nameOfDeceased: "WAMWERE MAKUMI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-25",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KENOL LAW COURTS",
},
{
  causeNo: "E085/2025",
  nameOfDeceased: "NKOITETE OLE NESIRIA KOTETE",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-30",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KILGORIS LAW COURTS",
},
{
  causeNo: "E084/2025",
  nameOfDeceased: "LEKOKUA OLE NESIRIA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-30",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KILGORIS LAW COURTS",
},
{
  causeNo: "E077/2025",
  nameOfDeceased: "EMMY CHEPKIRUI RONO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-11",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KERICHO HIGH COURT",
},
{
  causeNo: "E041/2025",
  nameOfDeceased: "KIMUTAI ARAP MAINA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-07-03",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KERICHO HIGH COURT",
},

// ========================================================================
// PAGE 99 - KERICHO HIGH, BOMET, NYANDO LAW COURTS
// ========================================================================
{
  causeNo: "E279/2004",
  nameOfDeceased: "BORONGENY ARAP MOSONIK",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-09-25",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KERICHO HIGH COURT",
},
{
  causeNo: "E210/2025",
  nameOfDeceased: "KIPKEMOI ARAP TUMIMISING",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-19",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "BOMET LAW COURTS",
},
{
  causeNo: "E195/2025",
  nameOfDeceased: "TAPNYOLE KIPLASOI ARAP SITONIK",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: undefined,
  form60Compliance: Form60Compliance.REJECTED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: "REJECTED",
  courtName: "BOMET LAW COURTS",
},
{
  causeNo: "E574/2025",
  nameOfDeceased: "HELIDA ATIENO OGWANG",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-24",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E491/2025",
  nameOfDeceased: "BARNABA ODERA SIRAMA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-12",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E370/2025",
  nameOfDeceased: "OGWANG ODECH",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-07-28",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E524/2025",
  nameOfDeceased: "ZEPHANIA OLOLA AGUMBA ZAPHANIA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-03",
  dateForwardedToGP: undefined,
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E066/2023",
  nameOfDeceased: "JECONIA OMOLO ODHENGO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2024-03-12",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E594/2025",
  nameOfDeceased: "MUGA OCHIEWO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-03",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},

// ========================================================================
// PAGE 100 - NYANDO LAW COURTS
// ========================================================================
{
  causeNo: "E452/2025",
  nameOfDeceased: "SILFANUS OKOTH OSEWO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-27",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E583/2025",
  nameOfDeceased: "SAMWEL ODHAMBO OCHIENG SAMUEL",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-21",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E605/2025",
  nameOfDeceased: "ALOYS GWADA ABONGO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-08",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E575/2025",
  nameOfDeceased: "ISAAC AJUNAG SIMBIRI ISACK AJWANG",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-20",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E604/2025",
  nameOfDeceased: "OTIENO ONYANGO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-08",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E561/2025",
  nameOfDeceased: "ODHIAMBO ATHALA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-11",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E390/2025",
  nameOfDeceased: "SILVANUS ODHAMBO NYATOGO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-09-02",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E599/2025",
  nameOfDeceased: "PAUL ODUOGO GOTI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-03",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E555/2025",
  nameOfDeceased: "JOHNSON AMBET OWINO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-24",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E588/2025",
  nameOfDeceased: "DALMAS OKWACH ABUYA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-24",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E591/2025",
  nameOfDeceased: "PETER OGEMBO ODONGO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-27",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},

// ========================================================================
// PAGE 101 - NYANDO, SIAYA LAW COURTS
// ========================================================================
{
  causeNo: "E582/2025",
  nameOfDeceased: "ALFRED ACHILA OWUOTH",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-21",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E564/2025",
  nameOfDeceased: "CHARLIS OGADA OCHICH",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-14",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E494/2025",
  nameOfDeceased: "SAMSON ANYANGO GOWI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-04",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E339/2025",
  nameOfDeceased: "LAZARO AOKO ODERO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-03",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E597/2025",
  nameOfDeceased: "JAGERO OREDO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-02",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E526/2025",
  nameOfDeceased: "EZAKIEL OKELO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-03",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NYANDO LAW COURTS",
},
{
  causeNo: "E576/2025",
  nameOfDeceased: "JASON OTIENO ODULA OTHIENO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-13",
  dateForwardedToGP: undefined,
  form60Compliance: Form60Compliance.REJECTED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: "REJECTED",
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E574/2025",
  nameOfDeceased: "ROSE HAMISI NAMEMA NAPHTALI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-05",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E573/2025",
  nameOfDeceased: "ZADOCK HIGWA SHADOCK",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-08",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E572/2025",
  nameOfDeceased: "OTEINO SEWE MALAKI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-05",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E571/2025",
  nameOfDeceased: "JAMES WILLIAM ODHIAMBO OKWAMA OTENG",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-05",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},

// ========================================================================
// PAGE 102 - SIAYA, MILIMANI, MOMBASA LAW COURTS
// ========================================================================
{
  causeNo: "E559/2025",
  nameOfDeceased: "PAUL SATCUS OTIENDE",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E558/2025",
  nameOfDeceased: "RANDIGA OKWANY",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E557/2025",
  nameOfDeceased: "ALFRED AUMA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E556/2025",
  nameOfDeceased: "LUKAS OBADIAH KWANZU",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E555/2025",
  nameOfDeceased: "JOHN ATITO OYANDA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E554/2025",
  nameOfDeceased: "WILLIAM MAGOLO ODHIER",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E553/2025",
  nameOfDeceased: "JACKTONE AMUKOA NAIKA WAMKOWA AMKOVA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E439/2025",
  nameOfDeceased: "EDITH AUMA OMBIMA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "SIAYA LAW COURTS",
},
{
  causeNo: "E940/2025",
  nameOfDeceased: "JAMES PATRICK TREFFRY FOSTER",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-21",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MILIMANI H.C FAMILY DIVISION",
},
{
  causeNo: "E633/2025",
  nameOfDeceased: "MILIKA MUKIMA MWAURA MILICA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-24",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MILIMANI H.C FAMILY DIVISION",
},
{
  causeNo: "E922/2025",
  nameOfDeceased: "ALBERT BEDA ONGARO",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-24",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MILIMANI H.C FAMILY DIVISION",
},

// ========================================================================
// PAGE 103 - MILIMANI, MOMBASA LAW COURTS
// ========================================================================
{
  causeNo: "E941/2025",
  nameOfDeceased: "HAIDERALI NAZERALI THOBANI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-11",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MILIMANI H.C FAMILY DIVISION",
},
{
  causeNo: "E637/2025",
  nameOfDeceased: "DAVID JOMO MUIGAI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-25",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MILIMANI H.C FAMILY DIVISION",
},
{
  causeNo: "E650/2025",
  nameOfDeceased: "RUTH WANGUI MWANGI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-10-07",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MILIMANI H.C FAMILY DIVISION",
},
{
  causeNo: "E1081/2024",
  nameOfDeceased: "MARY WANJIRU WANJAU",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-02-25",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MILIMANI H.C FAMILY DIVISION",
},
{
  causeNo: "E624/2024",
  nameOfDeceased: "LOISE WANGU CHEGGE KARIUKI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2024-09-19",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MILIMANI H.C FAMILY DIVISION",
},
{
  causeNo: "E090/2025",
  nameOfDeceased: "JOSEPH NYONGESA WELOBA",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-11-28",
  dateForwardedToGP: undefined,
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOMBASA HIGH COURT",
},
{
  causeNo: "E175/2025",
  nameOfDeceased: "MARGARET MBIYNA NZIMBI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-01",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOMBASA LAW COURTS",
},
{
  causeNo: "E230/2025",
  nameOfDeceased: "MOHAMED AHMED MOHAMED",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-11",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOMBASA LAW COURTS",
},
{
  causeNo: "E077/2025",
  nameOfDeceased: "ALLOYSIUS MUNYENI MUTETI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-08-12",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOMBASA LAW COURTS",
},
{
  causeNo: "E215/2025",
  nameOfDeceased: "JOSPHAT MULI KITONYI",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-10",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOMBASA LAW COURTS",
},
{
  causeNo: "E191/2025",
  nameOfDeceased: "BINYANYA ABDUL MOHAMED",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-10",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOMBASA LAW COURTS",
},

// ========================================================================
// PAGE 104 - MOMBASA, NAIROBI CHIEF MAGISTRATES COURTS
// ========================================================================
{
  causeNo: "E188/2025",
  nameOfDeceased: "EDWARD KARIOKI LENGEES",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-09",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOMBASA LAW COURTS",
},
{
  causeNo: "E075/2025",
  nameOfDeceased: "SERAH WANJIKU NJOROGE",
  dateOfReceipt: "2026-01-07",
  dateReceived: "2025-12-05",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "MOMBASA LAW COURTS",
},
{
  causeNo: "E291/2025",
  nameOfDeceased: "SAMUEL MARERI KAIRU",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-12-08",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.REJECTED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: "REJECTED",
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E692/2025",
  nameOfDeceased: "JANE WALI MWAISAKA",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-12-01",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E675/2025",
  nameOfDeceased: "BERNADETTE NYAMBURA NDUNGU",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-11-20",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E676/2025",
  nameOfDeceased: "GEORGE NGANGA NDUNGU",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-11-20",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E439/2025",
  nameOfDeceased: "HENRY AMENA AMUGUNI",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-08-01",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E487/2025",
  nameOfDeceased: "HANSABEN PRABHULAL SHAH",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-09-04",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E248/2025",
  nameOfDeceased: "ROSE ILHAVI MUJENDITSI",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-05-20",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},

// ========================================================================
// PAGE 105 - NAIROBI CHIEF MAGISTRATES COURT
// ========================================================================
{
  causeNo: "E256/2025",
  nameOfDeceased: "MARGIT KRISTINA FALKESTROM OCHOLLA AYAYO",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-04-28",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E436/2025",
  nameOfDeceased: "MADHUSUDAN ARVINDBHAI PATEL",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-10-15",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E709/2025",
  nameOfDeceased: "KARSAN GORDHAN CHHAYA",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-12-05",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E697/2025",
  nameOfDeceased: "JOHN MBOGO MBURU",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-12-08",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E724/2025",
  nameOfDeceased: "CLEOPHAS GATHU MUCHIRI",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-12-11",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E707/2025",
  nameOfDeceased: "KIMANI WAIHENYA",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-12-04",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E629/2025",
  nameOfDeceased: "MICHAEL MUHANJI MILIMU",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-12-18",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E633/2025",
  nameOfDeceased: "MILKA NDULU KALII",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-10-30",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},

// ========================================================================
// PAGE 106 - NAIROBI CHIEF MAGISTRATES COURT
// ========================================================================
{
  causeNo: "E538/2025",
  nameOfDeceased: "EMILIO MUCHANGI NJAGI",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-10-14",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E532/2024",
  nameOfDeceased: "VITALIS OURU OWAGA",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-09-10",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E398/2024",
  nameOfDeceased: "JAMES WAIGWA WAMBUGU",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2024-09-09",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E645/2025",
  nameOfDeceased: "JOSEPH NZIOKI MAKAU",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-11-06",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E689/2025",
  nameOfDeceased: "CATHERINE MUTINDI MUTHUSI",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-11-26",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E592/2025",
  nameOfDeceased: "GIDEON NYAMWEYA NYAANGA",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-10-02",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E493/2025",
  nameOfDeceased: "TERESA MORAIA TOME",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-10-27",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E215/2025",
  nameOfDeceased: "HELLEN MUKHAVI MWISHENI",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-12-03",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E638/2025",
  nameOfDeceased: "JARED OMUSULA",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-11-06",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},

// ========================================================================
// PAGE 107 - NAIROBI CHIEF MAGISTRATES, KWALE, RUIRU LAW COURTS
// ========================================================================
{
  causeNo: "E683/2025",
  nameOfDeceased: "JOHNSON KANYONGE MACHARO",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-11-26",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E165/2025",
  nameOfDeceased: "JOHN MWALE",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-03-12",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E685/2025",
  nameOfDeceased: "OLUOCH OBURA",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-11-24",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E372/2025",
  nameOfDeceased: "POLYCARP JUDRAPH WANYOIKE POLYCORP",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2024-04-09",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E681/2025",
  nameOfDeceased: "CAROLINE NJERU JESSIE MUTHONI",
  dateOfReceipt: "2026-01-06",
  dateReceived: "2025-11-21",
  dateForwardedToGP: "2026-01-09",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "NAIROBI CHIEF MAGISTRATES COURT",
},
{
  causeNo: "E040/2025",
  nameOfDeceased: "THOMAS CHIGAMBA NGUTA",
  dateOfReceipt: "2026-01-08",
  dateReceived: "2025-10-30",
  dateForwardedToGP: "2026-01-16",
  form60Compliance: Form60Compliance.APPROVED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: undefined,
  courtName: "KWALE LAW COURTS",
},
{
  causeNo: "E015/2025",
  nameOfDeceased: "HANNAH WAIRIMU JUMA",
  dateOfReceipt: "2026-01-15",
  dateReceived: "2025-03-04",
  dateForwardedToGP: undefined,
  form60Compliance: Form60Compliance.REJECTED,
  statusAtGP: StatusAtGP.PENDING,
  rejectionReason: "REJECTED",
  courtName: "RUIRU LAW COURTS",
},

];

// ─── SEED FUNCTION ────────────────────────────────────────────────────────────

async function seed() {
  await mongoose.connect(MONGO_URI, ...(DB_NAME ? [{ dbName: DB_NAME }] : []));
  console.log(
    "✅ Connected to MongoDB:",
    MONGO_URI,
    "| DB:",
    mongoose.connection.name,
  );

  const uniqueCourtNames = [...new Set(RAW_RECORDS.map((r) => r.courtName))];
  const courtMap = new Map<string, mongoose.Types.ObjectId>();

  for (const name of uniqueCourtNames) {
    const court = await Court.findOne({ name: new RegExp(`^${name}$`, "i") });
    if (!court) {
      const all: { name: string }[] = await Court.find(
        {},
        { name: 1 },
      ).lean();
      console.error(`❌ Court '${name}' not found.`);
      console.error(
        "Courts in DB:",
        all.map((c) => `"${c.name}"`).join(", "),
      );
      await mongoose.disconnect();
      process.exit(1);
    }
    courtMap.set(name, court._id);
    console.log(`✅ Found court: ${court.name} (${court._id})`);
  }

  const lastRecord = await Record.findOne().sort({ no: -1 }).select("no");
  let nextNo = lastRecord ? lastRecord.no + 1 : 1;
  console.log(`ℹ️  Starting record no from: ${nextNo}`);

  let inserted = 0;
  let skipped = 0;
  let failed = 0;

  for (const raw of RAW_RECORDS) {
    const courtId = courtMap.get(raw.courtName)!;

    try {
      const exists = await Record.findOne({
        courtStation: courtId,
        causeNo: raw.causeNo.toUpperCase(),
      });

      if (exists) {
        console.log(
          `⚠️  Skipping duplicate: ${raw.causeNo} — ${raw.nameOfDeceased}`,
        );
        skipped++;
        continue;
      }

      const doc = new Record({
        no: nextNo++,
        courtStation: courtId,
        causeNo: raw.causeNo,
        nameOfDeceased: raw.nameOfDeceased,
        dateReceived: new Date(raw.dateReceived),
        dateOfReceipt: new Date(raw.dateOfReceipt),
        dateForwardedToGP: raw.dateForwardedToGP
          ? new Date(raw.dateForwardedToGP)
          : undefined,
        form60Compliance: raw.form60Compliance,
        statusAtGP: raw.statusAtGP,
        rejectionReason: raw.rejectionReason,
        kpiAlertSent: false,
      });

      await doc.save();
      console.log(
        `✅ Inserted [${doc.no}] ${raw.causeNo} — ${raw.nameOfDeceased}`,
      );
      inserted++;
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(
        `❌ Failed: ${raw.causeNo} — ${raw.nameOfDeceased}:`,
        message,
      );
      failed++;
    }
  }

  console.log(`\n🎉 Done.`);
  console.log(`   ✅ Inserted:  ${inserted}`);
  console.log(`   ⚠️  Skipped:   ${skipped} (duplicates)`);
  console.log(`   ❌ Failed:    ${failed}`);
  await mongoose.disconnect();
}

seed().catch((err: unknown) => {
  console.error(
    "Fatal error:",
    err instanceof Error ? err.message : String(err),
  );
  process.exit(1);
});